services:
  - type: web
    name: it-placement-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: it-placement-db
          property: connectionString

databases:
  - name: it-placement-db
    databaseName: it_placement
    user: it_placement_user
